- name: Create a file and add content using copy
  become: yes
  become_user: root
  tasks:
    - name: Create file and add content
      ansible.builtin.copy:
        content: "test salla3\n"
        dest: /tmp/tr.txt
    - name: fetch file
      fetch:
          src: /tmp/tr.txt
          dest: /tmp/