- name: Create a file and add content using copy
  hosts: 10.10.55.15
  tasks:
    - name: Create file and add content
      ansible.builtin.copy:
        content: "test salla2\n"
        dest: /tmp/tr.txt
    - name: fetch file
      fetch:
          src: /tmp/tr.txt
          dest: /tmp/